detect missing potrace/autotrace. (PYTHON): release 1.1.6

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,6 +6,13 @@ AC_PATH_PROG(AUTOTRACE, autotrace, none)
 AC_PATH_PROG(POTRACE, potrace, none)
 AC_SUBST(PYTHON)
 
+if test "$POTRACE" = "none" -a "$AUTOTRACE" = "none"  ; then
+    echo ''
+    echo ' ERROR: install potrace or autotrace' 
+    echo ''
+    exit 1
+fi 
+	
 export VERSION="1.1.6"
 
 AC_SUBST(VERSION)
@@ -18,8 +25,3 @@ AC_OUTPUT(GNUmakefile:GNUmakefile.in mftrace:mftrace.py mftrace.spec:mftrace.spe
 chmod a-w GNUmakefile mftrace
 chmod a+x mftrace
 
-if test "$POTRACE" = "none" -a "$AUTOTRACE" = "none"  ; then
-    echo ''
-    echo ' ERROR: install potrace or autotrace' 
-    echo ''
-fi 
